#!/bin/sh
#
# Start the network....
#

case "$1" in
	start)
		echo "Starting network..."
		[ -d /var/run/network ] || mkdir /var/run/network

		[ -f /var/run/network/ifstate ] || touch /var/run/network/ifstate
		/sbin/ifup -a
	;;
	stop)
		echo -n "Stopping network..."
		/sbin/ifdown -a
		;;
	restart|reload)
		"$0" stop
		"$0" start
		;;
	*)
	echo $"Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
